spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 1.5
          max-interval: 5000
        concurrency: 50
        max-concurrency: 100

application:
  amqp:
    queue:
      test: test-queue